name: 'Extract Tag Details'
description: 'Extract tag details and create a description.'
inputs:
  full_tag_ref:
    description: 'The full tag reference (e.g., refs/tags/v1.0.0)'
    required: true
outputs:
  tag_name:
    description: 'The name of the tag'
    value: ${{ steps.extract_tag.outputs.tag_name }}
  tag_message:
    description: 'The message attached to the tag'
    value: ${{ steps.get_tag_message.outputs.tag_message }}
runs:
  using: 'composite'
  steps:
    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: |
        TAG_NAME=${INPUT_FULL_TAG_REF#refs/tags/}
        echo "Extracted tag name: $TAG_NAME"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Get tag message
      id: get_tag_message
      shell: bash
      run: |
        TAG_NAME=${INPUT_FULL_TAG_REF#refs/tags/}
        TAG_MESSAGE=$(git tag -l --format='%(contents)' $TAG_NAME)
        echo "Extracted tag message: $TAG_MESSAGE"
        echo "tag_message=$TAG_MESSAGE" >> $GITHUB_OUTPUT