name: 'Extract Tag Details'
description: 'Extract tag details and write the tag message to a file.'
inputs:
  full_tag_ref:
    description: 'The full tag reference (e.g., refs/tags/v1.0.0)'
    required: true
outputs:
  tag_name:
    description: 'The name of the tag'
    value: ${{ steps.extract_tag.outputs.tag_name }}
  tag_message_file:
    description: 'The path to the file containing the tag message'
    value: ${{ steps.get_tag_message.outputs.tag_message_file }}
runs:
  using: 'composite'
  steps:
    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: |
        TAG_NAME=${INPUT_FULL_TAG_REF#refs/tags/}
        echo "Extracted tag name: $TAG_NAME"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Get tag message
      id: get_tag_message
      shell: bash
      run: |
        TAG_NAME=${INPUT_FULL_TAG_REF#refs/tags/}
        TAG_MESSAGE=$(git tag -l --format='%(contents)' $TAG_NAME)

        # Write the tag message to a file
        TAG_MESSAGE_FILE="tag_message.txt"
        echo "$TAG_MESSAGE" > $TAG_MESSAGE_FILE
        echo "Tag message written to: $TAG_MESSAGE_FILE"
        echo "tag_message_file=$TAG_MESSAGE_FILE" >> $GITHUB_OUTPUT