name: Detect Release Commit

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect-release-commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Extract PR title and body
        id: extract-pr
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          # Save PR title and body as output variables
          echo "pr_title=${PR_TITLE}" >> $GITHUB_OUTPUT
          echo "pr_body=${PR_BODY}" >> $GITHUB_OUTPUT

          # Check if PR title or body starts with "release:"
          if [[ "$PR_TITLE" != release:* && "$PR_BODY" != release:* ]]; then
            echo "Neither PR title nor body starts with 'release:'"
            echo "Stopping pipeline with success status..."
            exit 0 # Exit with success status
          else
            echo "PR title or body starts with 'release:'"
            echo "Continuing pipeline..."
          fi

      - name: Print PR title and body
        run: |
          echo "PR Title: ${{ steps.extract-pr.outputs.pr_title }}"
          echo "PR Body: ${{ steps.extract-pr.outputs.pr_body }}"

      - name: Continue pipeline
        if: steps.extract-pr.outcome == 'success'
        run: |
          echo "Pipeline continues..."
          # Add your pipeline steps here
          
          
          

      - name: Trigger next workflow
        if: steps.check-commit.outputs.is_release_commit == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-detected
          client-payload: '{"pull_request": {"merge_commit": {"message": "${{ github.event.pull_request.merge_commit.message }}"}}}'