name: 'Extract PR Details'
description: 'Extract PR Details'
runs:
  using: 'composite'
  steps:
    - name: Extract PR Details
      shell: bash
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"

        # Save PR title and body as output variables
        echo "pr_title=${PR_TITLE}" >> $GITHUB_OUTPUT
        echo "pr_body=${PR_BODY}" >> $GITHUB_OUTPUT

        # Check if PR title or body starts with "release:"
        if [[ "$PR_TITLE" != release:* && "$PR_BODY" != release:* ]]; then
          echo "Neither PR title nor body starts with 'release:'"
          echo "Stopping pipeline with fail status..."
          exit 1 # Exit with fail status
        else
          echo "PR title or body starts with 'release:'"
          echo "Continuing pipeline..."
        fi