name: 'Extract PR Details'
description: 'Extract PR Details'
runs:
  using: 'composite'
  steps:
    - name: Extract PR Details
      id: extract-step
      shell: bash
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"

        # Escape newlines in PR_BODY
        PR_BODY_ESCAPED=$(echo "$PR_BODY" | sed ':a;N;$!ba;s/\n/%0A/g')

        # Save PR title and body as action outputs
        echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
        echo "pr_body=$PR_BODY_ESCAPED" >> $GITHUB_OUTPUT

        # Check for "release:" prefix
        if [[ "$PR_TITLE" != "release:"* ]]; then
          echo "PR not a release. Stopping pipeline..."
          exit 1
        fi

# Define action outputs
outputs:
  pr_title:
    description: 'PR title'
    value: ${{ steps.extract-step.outputs.pr_title }}
  pr_body:
    description: 'PR body'
    value: ${{ steps.extract-step.outputs.pr_body }}