name: 'Notify Discord About Release'
description: 'Send a Discord notification for a new release.'
runs:
  using: 'composite'
  steps:
    - name: Send Discord Notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ inputs.discord_webhook }}
      with:
        args: |
          🚀 **${{ inputs.os }} Release Published!**
          
          📦 Version:  Release ${{ inputs.tag_name }}       
             Details:
             ${{ inputs.release_body }}       
          
          📥 *Download Link:*
          [Download ${{ inputs.os }} Build](${{ inputs.download_link }})
          
          🔍 [View Release](${{ inputs.release_link }})

inputs:
  discord_webhook:
    description: 'The Discord webhook URL'
    required: true
  os:
    description: 'The operating system (e.g., macOS, Linux, Windows).'
    required: true
  download_link:
    description: 'The download link for the release asset.'
    required: true
  release_link:
    description: 'The link to the GitHub release.'
    required: true
  tag_name:
    description: 'The name of the tag'
    required: true
  release_body:
    description: 'The body message of the tag'
    required: true