name: Validation Assets
on:
  pull_request:
    branches:
      - main
jobs:
  validation_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
      - name: Install dependencies
        run: flutter pub get
      - name: Generate Assets Files
        run: |
          # Command to rebuild asset files
          dart run build_runner build --delete-conflicting-outputs --build-filter="lib/src/core/utils/gen/assets\*.dart" || (
            echo "Error: Failed to generate asset files.";
            exit 1;
          )
      - name: Check Asset Files Changes
        run: |
          # Check if there are changes after generating asset files
          git diff --exit-code lib/src/core/utils/gen/assets || (
            echo "Error: Asset files are outdated. Run the generation command and commit the changes.";
            exit 1;
          )