name: Linux Release Build

# Add environment variables at the top level
env:
  LINUX_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_linux_amd64.tar.gz"

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.2.3

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: get_tag_name
        shell: bash
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag name: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Get and prepare tag message
        id: get_tag_message
        shell: bash
        run: |
          # Extract tag name
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Get the tag message
          TAG_MESSAGE=$(git tag -l --format='%(contents)' $TAG_NAME)
          
          # Write the tag message to a file (optional, if you still need the file)
          TAG_MESSAGE_FILE="tag_message.txt"
          echo "$TAG_MESSAGE" > $TAG_MESSAGE_FILE
          echo "Tag message written to: $TAG_MESSAGE_FILE"
          
          # Set the release body as an output
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true

      - name: Install Flutter dependencies
        uses: ./.github/actions/preparing-release

      - name: Install Linux dependencies
        uses: ./.github/actions/linux-install-dependencies

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Fetch and Extract Files
        uses: ./.github/actions/linux-extract-files

      - name: Build application
        run: flutter build linux --release

      - name: Linux Release
        id: linux_release
        uses: ./.github/actions/linux-release
        with:
          tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
          release_name: ${{ steps.get_tag_name.outputs.tag_name }}
          release_body:  ${{ steps.get_tag_message.outputs.release_body}}

          github_token: ${{ secrets.GITHUB_TOKEN }} # Pass the secret as an input

      - name: Archive Linux Build Files
        id: archive_linux_build
        shell: bash
        run: |
          # Navigate to the build directory
          cd build/linux/x64/release/bundle
          
          # Create a zip archive with the correct file name
          FILE_NAME="linux-build-${{ steps.extract_tag.outputs.tag_name }}.zip"
          zip -r "${FILE_NAME}" .
          
          # Set the file name as an output
          echo "file_name=${FILE_NAME}" >> $GITHUB_OUTPUT

      - name: Create Linux Release
        id: create_linux_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          release_name: "${{ inputs.release_name }}"
          body: "${{ inputs.release_body }}"
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        id: upload_linux_release_asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          files: build/linux/x64/release/bundle/${{ steps.archive_linux_build.outputs.file_name }}

      - name: Prepare Download Links
        id: prepare_download_links
        uses: ./.github/actions/prepare-download-links
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          file_name: ${{ steps.archive_linux_build.outputs.file_name }}


      - name: Send Discord Notification
        uses: ./.github/actions/notification-to-discord
        with:
          os: Linux
          download_link: ${{ steps.prepare_download_links.outputs.download_link }}
          release_link: ${{ steps.prepare_download_links.outputs.release_link }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
