name: Linux Release Build (x64/AppImage)

on:
  push:
    tags:
      - 'v*'

# Add environment variables at the top level
env:
  LINUX_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.7.1/pactus-cli_1.7.1_linux_amd64.tar.gz"

permissions:
  contents: write

jobs:
  build-and-release-linux-amd64:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'

      - name: 01 - Install Dependencies
        run: bash .github/scripts/linux/01-install-dependencies.sh

      - name: 02 - Install Flutter Project Dependencies
        run: bash .github/scripts/linux/02-install-flutter-deps.sh

      - name: 03 - Build Flutter Linux Bundle
        run: bash .github/scripts/linux/03-build.sh

      - name: 04 - Extract daemon files
        run: bash .github/scripts/linux/04-extract-daemon-files.sh

      - name: 04 - Prepare AppDir and Collect Files
        run: bash .github/scripts/linux/05-prepare-appdir.sh

      - name: 05 - Download AppImage Tools
        run: bash .github/scripts/linux/06-download-tools.sh

      - name: 07 - Build AppImage
        run: bash .github/scripts/linux/07-build-appimage.sh

      - name: 08 - Test AppImage (headless)
        run: bash .github/scripts/linux/08-test.sh

      - name: Upload Built AppImage
        uses: actions/upload-artifact@v4
        with:
          name: PactusGUI-AppImage
          path: ./*.AppImage


      - name: Get Tag Data
        id: tag_data
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          ARCH="x86_64"
          FILE_NAME="pactus_gui-${TAG_NAME}-${ARCH}.AppImage"
          TAG_MESSAGE=$(git tag -l --format='%(contents)' "$TAG_NAME" || echo "No release notes")
        
          # Escape for GitHub Actions output
          TAG_MESSAGE="${TAG_MESSAGE//'%'/'%25'}"
          TAG_MESSAGE="${TAG_MESSAGE//$'\n'/'%0A'}"
        
          echo "file_name=${FILE_NAME}" >> $GITHUB_OUTPUT
          echo "tag_message=${TAG_MESSAGE}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_data.outputs.tag_name }}
          release_name: "Release ${{ steps.tag_data.outputs.tag_name }}"
          body: |
            ${{ steps.tag_data.outputs.tag_message }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload AppImage
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          tag_name: ${{ steps.tag_data.outputs.tag_name }}


#      - name: Get Tag Message
#        id: get_tag_message
#        run: |
#          TAG_NAME=${GITHUB_REF#refs/tags/}
#          ARCH="x86_64"
#          FILE_NAME="pactus_gui-${TAG_NAME}-${ARCH}.AppImage"
#          TAG_MESSAGE=$(git tag -l --format='%(contents)' "$TAG_NAME")
#          # Escape newlines for GitHub Actions output
#          TAG_MESSAGE="${TAG_MESSAGE//'%'/'%25'}"
#          TAG_MESSAGE="${TAG_MESSAGE//$'\n'/'%0A'}"
#          echo "tag_message=$TAG_MESSAGE" >> $GITHUB_OUTPUT
#
#
#      - name: Create Windows Release
#        uses: softprops/action-gh-release@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ GITHUB_REF#refs/tags/ }}
#          release_name: "${{ inputs.release_name }}"
#          body: "${{ inputs.release_body }}"
#          draft: false
#          prerelease: false
#
#      - name: Upload Windows Release Asset
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ inputs.tag_name }}
#          files: ./${{}}
#  "pactus_gui-${TAG}-${ARCH}.AppImage"
