name: Desktop Release Build

# Add environment variables at the top level
env:
  LINUX_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_linux_amd64.tar.gz"
  WINDOWS_AMD64_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_windows_amd64.zip"
  WINDOWS_386_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_windows_386.zip"
  MACOS_ARM64_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_darwin_arm64.tar.gz"
  MACOS_AMD64_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_darwin_amd64.tar.gz"

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.2.3

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Tag Details
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          echo "title=${TAG_NAME}" >> $GITHUB_ENV
          echo "description=Automated release for $TAG_NAME" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true

      - name: Install Linux dependencies
        uses: ./.github/actions/linux-install-dependencies

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Localization Files
        uses: ./.github/actions/generate-localization

      - name: Generate Asset Files
        uses: ./.github/actions/generate-assets

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Fetch and Extract Files
        uses: ./.github/actions/linux-extract-files

      - name: Build application
        run: flutter build linux --release

      - name: Linux Archive Release
        uses: ./.github/actions/linux-archive-release

      - name: Rename Linux Build File
        run: |
          mv build/linux/x64/release/bundle/linux-build.zip build/linux/x64/release/bundle/linux-build-${{ env.tag_name }}.zip

      - name: Create Linux Release
        id: create_linux_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: "${{ env.title }}"
          body: "${{ env.description }}"
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          files: build/linux/x64/release/bundle/linux-build-${{ env.tag_name }}.zip
