name: Detect Release Commit

runs-on: ubuntu-latest

outputs:
  is_release_commit: ${{ steps.check-commit.outputs.is_release_commit }}

steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Check merge commit message
    id: check-commit
    run: |
      if [[ "${{ github.event.pull_request.merge_commit_message }}" == release:\ create\ release\ for* ]]; then
        echo "is_release_commit=true" >> $GITHUB_OUTPUT
      else
        echo "is_release_commit=false" >> $GITHUB_OUTPUT
      fi