name: Extract Version and Changelog

on:
  repository_dispatch:
    types:
      - release-detected

jobs:
  extract-version-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Extract version
        id: extract-version
        run: |
          VERSION=$(echo "${{ github.event.client_payload.pull_request.merge_commit.message }}" | grep -oP '(?<=release: create release for )v[0-9]+\.[0-9]+\.[0-9]+')
          echo "::set-output name=version::$VERSION"

      - name: Extract changelog
        id: extract-changelog
        run: |
          CHANGELOG=$(echo "${{ github.event.client_payload.pull_request.merge_commit.message }}" | sed -n '/release: create release for/{:a;N;/---/!ba;s/.*\n\n//p}')
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Trigger next workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: version-extracted
          client-payload: '{"version": "${{ steps.extract-version.outputs.version }}", "changelog": "${{ steps.extract-changelog.outputs.changelog }}"}'