name: Build Outputs

runs-on: ubuntu-latest

needs: create-tag

steps:
  - name: Checkout repository
    uses: actions/checkout@v3

#  - name: Build for Android
#    run: echo "Building for Android..."

#  - name: Build for iOS
#   run: echo "Building for iOS..."

#  - name: Build for Web
#    run: echo "Building for Web..."
   - name: Build for Linux
     run: flutter build linux --release
