name: Detect Release Commit

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect-release-commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check merge commit message
        id: check-commit
        run: |
          if [[ "${{ github.event.pull_request.merge_commit.message }}" == release:\ create\ release\ for* ]]; then
            echo "::set-output name=is_release_commit::true"
          else
            echo "::set-output name=is_release_commit::false"
          fi

      - name: Trigger next workflow
        if: steps.check-commit.outputs.is_release_commit == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-detected